import React from 'react'
import {
  Accordion,
  AccordionContent,
  AccordionItem,
  AccordionTrigger,
} from "@/components/ui/accordion"

const Faqs = () => {
  const faqs = [
    {
      question: "What is an AI-powered resume generator?",
      answer:
        "It's a smart tool that helps you create a professional resume in minutes using AI. It tailors content based on your experience, skills, and the job you're applying for.",
    },
    {
      question: "Can I customize my resume and cover letter?",
      answer:
        "Yes! You can edit and personalize the content generated by AI to better reflect your voice and style before downloading or sharing.",
    },
    {
      question: "Are the industry insights updated regularly?",
      answer:
        "Absolutely. Our platform pulls real-time data to provide you with the latest trends, salary ranges, and skill demands in various industries.",
    },
    {
      question: "How does the interview preparation work?",
      answer:
        "We offer AI-driven mock interviews, common questions based on your target role, and instant feedback to help you prepare effectively.",
    },
    {
      question: "Is it free to use?",
      answer:
        "We offer a free tier with basic features. Premium features like advanced templates and detailed interview coaching are available with a subscription.",
    },
    {
      question: "Can I download my documents?",
      answer:
        "Yes, you can download your resume and cover letter as PDF files at any time.",
    },
  ];

  return (
    <section className="relative py-16 px-4 z-10">
      <div className="text-center mb-10">
        <h2 className="text-3xl font-bold mb-4">Frequently Asked Questions</h2>
        <p className="text-gray-600">Answers to the most common questions about our platform and tools.</p>
      </div>

      <div className="font-mono max-w-5xl md:max-w-3xl sm:max-w-xl mx-auto">
        <Accordion type="single" collapsible className='w-full'>
          {faqs.map((item, index) => (
            <AccordionItem key={index} value={`item-${index}`}>
              <AccordionTrigger>{item.question}</AccordionTrigger>
              <AccordionContent>{item.answer}</AccordionContent>
            </AccordionItem>
          ))}
        </Accordion>
      </div>
    </section>
  )
}

export default Faqs